p8105_hw2_th3147
================
Te-Hsuan Huang
2025-09-27

# Problem 1

1.  First dataset

``` r
library(tidyverse)

polsmonth_df = read_csv(file = "./fivethirtyeight_datasets/pols-month.csv") |> 
  janitor::clean_names() |> 
  separate(mon, into = c("year", "month", "day"), sep = "-") |> 
 mutate( 
   year = as.numeric(year),
    month = case_match(
      month,
      "01" ~ "jan",
      "02" ~ "feb",
      "03" ~ "mar",
      "04" ~ "apr",
      "05" ~ "may",
      "06" ~ "jun",
      "07" ~ "jul",
      "08" ~ "aug",
      "09" ~ "sep",
      "10" ~ "oct",
      "11" ~ "nov",
      "12" ~ "dec"
    ), 
    president = case_match(
      prez_dem,
      1 ~ "dem",
      0 ~ "gop")) |> 
    select(-prez_dem, -prez_gop, -day)

polsmonth_df
```

    ## # A tibble: 822 × 9
    ##     year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <dbl> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 jan        23      51     253      23      45     198 dem      
    ##  2  1947 feb        23      51     253      23      45     198 dem      
    ##  3  1947 mar        23      51     253      23      45     198 dem      
    ##  4  1947 apr        23      51     253      23      45     198 dem      
    ##  5  1947 may        23      51     253      23      45     198 dem      
    ##  6  1947 jun        23      51     253      23      45     198 dem      
    ##  7  1947 jul        23      51     253      23      45     198 dem      
    ##  8  1947 aug        23      51     253      23      45     198 dem      
    ##  9  1947 sep        23      51     253      23      45     198 dem      
    ## 10  1947 oct        23      51     253      23      45     198 dem      
    ## # ℹ 812 more rows

- Note:

  - make sure the lower case in month.

2.  second dataset

``` r
snp_df = read_csv(file = "./fivethirtyeight_datasets/snp.csv") |> 
  janitor::clean_names() |> 
  separate(date, into = c("month", "day", "year"), sep = "/") |>
  mutate(
    year = as.integer(paste0("20", year)),
    year = as.numeric(year),
    month = case_match(
      month,
      "1" ~ "jan",
      "2" ~ "feb",
      "3" ~ "mar",
      "4" ~ "apr",
      "5" ~ "may",
      "6" ~ "jun",
      "7" ~ "jul",
      "8" ~ "aug",
      "9" ~ "sep",
      "10" ~ "oct",
      "11" ~ "nov",
      "12" ~ "dec"
    )) |> 
      select(-day) |>
      arrange (year, month) |> 
      relocate(year, month)

snp_df
```

    ## # A tibble: 787 × 3
    ##     year month close
    ##    <dbl> <chr> <dbl>
    ##  1  2000 apr   1452.
    ##  2  2000 aug   1518.
    ##  3  2000 dec   1320.
    ##  4  2000 feb   1366.
    ##  5  2000 jan   1394.
    ##  6  2000 jul   1431.
    ##  7  2000 jun   1455.
    ##  8  2000 mar   1499.
    ##  9  2000 may   1421.
    ## 10  2000 nov   1315.
    ## # ℹ 777 more rows

- Note:

  - paste0: is a function in R used to concatenate (join together)
    character strings.

  - make sure the lower case in month.

3.  Third dataset

``` r
unemploy_df = read_csv(file = "./fivethirtyeight_datasets/unemployment.csv") |> 
  janitor::clean_names() |> 
  pivot_longer(
    jan:dec,
    names_to = "month", 
    values_to = "unemployment_rate") |> 
  relocate(year, month) |>
  arrange(year, month)

unemploy_df
```

    ## # A tibble: 816 × 3
    ##     year month unemployment_rate
    ##    <dbl> <chr>             <dbl>
    ##  1  1948 apr                 3.9
    ##  2  1948 aug                 3.9
    ##  3  1948 dec                 4  
    ##  4  1948 feb                 3.8
    ##  5  1948 jan                 3.4
    ##  6  1948 jul                 3.6
    ##  7  1948 jun                 3.6
    ##  8  1948 mar                 4  
    ##  9  1948 may                 3.5
    ## 10  1948 nov                 3.8
    ## # ℹ 806 more rows

4.  Merge the dataset

``` r
final_merged_df = 
   polsmonth_df |>
  left_join(snp_df, by = c("year", "month")) |>
  left_join(unemploy_df, by = c("year", "month"))

final_merged_df
```

    ## # A tibble: 822 × 11
    ##     year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##    <dbl> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ##  1  1947 jan        23      51     253      23      45     198 dem          NA
    ##  2  1947 feb        23      51     253      23      45     198 dem          NA
    ##  3  1947 mar        23      51     253      23      45     198 dem          NA
    ##  4  1947 apr        23      51     253      23      45     198 dem          NA
    ##  5  1947 may        23      51     253      23      45     198 dem          NA
    ##  6  1947 jun        23      51     253      23      45     198 dem          NA
    ##  7  1947 jul        23      51     253      23      45     198 dem          NA
    ##  8  1947 aug        23      51     253      23      45     198 dem          NA
    ##  9  1947 sep        23      51     253      23      45     198 dem          NA
    ## 10  1947 oct        23      51     253      23      45     198 dem          NA
    ## # ℹ 812 more rows
    ## # ℹ 1 more variable: unemployment_rate <dbl>

- Note:

  - the features of year and month in each dataset should be same.

  - the alphabet should be exactly same in month.

- The resulting dataset is a time-series data frame created by merging
  three original sources: pols-month.csv, which contains U.S. political
  control data (including the number of Democratic and Republican
  governors and the party of the sitting President); snp.csv, which
  tracks the S&P 500 closing price; and unemployment.csv, which records
  the national unemployment rate. After joining the three files on the
  common keys of year and month, the final merged dataset contains 822
  rows and 11 columns, covering the time span from 1947 to 2015. Key
  variables include the date identifiers (year, month), political
  metrics (gov_gop, rep_dem, president), the financial index (close),
  and the economic indicator (unemployment_rate).

# Problem 2

1.  First dataset

``` r
mrtrash_df = 
  readxl::read_excel("./problem 2/202509 Trash Wheel Collection Data.xlsx"
                     , sheet="Mr. Trash Wheel"
                     , range = "A2:N653") |> 
  janitor::clean_names() |> 
   mutate(
    sports_balls = as.integer(round(as.numeric(`sports_balls`))),
    wheel_name = "Mr. Trash Wheel",
    year=as.numeric(year)
  ) |> 
  select(-dumpster) |> 
  relocate(year, month, wheel_name) |> 
  arrange(date)

mrtrash_df
```

    ## # A tibble: 651 × 14
    ##     year month wheel_name     date                weight_tons volume_cubic_yards
    ##    <dbl> <chr> <chr>          <dttm>                    <dbl>              <dbl>
    ##  1  2014 May   Mr. Trash Whe… 2014-05-16 00:00:00        4.31                 18
    ##  2  2014 May   Mr. Trash Whe… 2014-05-16 00:00:00        2.74                 13
    ##  3  2014 May   Mr. Trash Whe… 2014-05-16 00:00:00        3.45                 15
    ##  4  2014 May   Mr. Trash Whe… 2014-05-17 00:00:00        3.1                  15
    ##  5  2014 May   Mr. Trash Whe… 2014-05-17 00:00:00        4.06                 18
    ##  6  2014 May   Mr. Trash Whe… 2014-05-20 00:00:00        2.71                 13
    ##  7  2014 May   Mr. Trash Whe… 2014-05-21 00:00:00        1.91                  8
    ##  8  2014 May   Mr. Trash Whe… 2014-05-28 00:00:00        3.7                  16
    ##  9  2014 June  Mr. Trash Whe… 2014-06-05 00:00:00        2.52                 14
    ## 10  2014 June  Mr. Trash Whe… 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 641 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>

2.  Second dataset

``` r
prtrash_df = 
  readxl::read_excel("./problem 2/202509 Trash Wheel Collection Data.xlsx"
                     , sheet="Professor Trash Wheel"
                     , range = "A2:M120") |> 
  janitor::clean_names() |> 
  mutate(
    wheel_name = "Professor Trash Wheel") |> 
  select(-dumpster) |> 
  relocate(year, month, wheel_name) |> 
  arrange(date)

prtrash_df
```

    ## # A tibble: 118 × 13
    ##     year month    wheel_name  date                weight_tons volume_cubic_yards
    ##    <dbl> <chr>    <chr>       <dttm>                    <dbl>              <dbl>
    ##  1  2017 January  Professor … 2017-01-02 00:00:00        1.79                 15
    ##  2  2017 January  Professor … 2017-01-30 00:00:00        1.58                 15
    ##  3  2017 February Professor … 2017-02-26 00:00:00        2.32                 18
    ##  4  2017 February Professor … 2017-02-26 00:00:00        3.72                 15
    ##  5  2017 February Professor … 2017-02-28 00:00:00        1.45                 15
    ##  6  2017 March    Professor … 2017-03-30 00:00:00        1.71                 15
    ##  7  2017 April    Professor … 2017-04-01 00:00:00        1.82                 15
    ##  8  2017 April    Professor … 2017-04-20 00:00:00        2.37                 15
    ##  9  2017 May      Professor … 2017-05-10 00:00:00        2.64                 15
    ## 10  2017 May      Professor … 2017-05-26 00:00:00        2.78                 15
    ## # ℹ 108 more rows
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>

3.  Third dataset

``` r
gwtrash_df = 
  readxl::read_excel("./problem 2/202509 Trash Wheel Collection Data.xlsx"
                     , sheet="Gwynns Falls Trash Wheel"
                     , range = "A2:L265") |> 
  janitor::clean_names() |> 
  mutate(
    wheel_name = "Gwynns Falls Trash Wheel") |> 
  select(-dumpster) |> 
  relocate(year, month, wheel_name) |> 
  arrange(date)
  
gwtrash_df
```

    ## # A tibble: 263 × 12
    ##     year month  wheel_name    date                weight_tons volume_cubic_yards
    ##    <dbl> <chr>  <chr>         <dttm>                    <dbl>              <dbl>
    ##  1  2021 July   Gwynns Falls… 2021-07-03 00:00:00        0.93                 15
    ##  2  2021 July   Gwynns Falls… 2021-07-07 00:00:00        2.26                 15
    ##  3  2021 July   Gwynns Falls… 2021-07-07 00:00:00        1.62                 15
    ##  4  2021 July   Gwynns Falls… 2021-07-16 00:00:00        1.76                 15
    ##  5  2021 July   Gwynns Falls… 2021-07-30 00:00:00        1.53                 15
    ##  6  2021 August Gwynns Falls… 2021-08-11 00:00:00        2.06                 15
    ##  7  2021 August Gwynns Falls… 2021-08-14 00:00:00        1.9                  15
    ##  8  2021 August Gwynns Falls… 2021-08-16 00:00:00        2.16                 15
    ##  9  2021 August Gwynns Falls… 2021-08-16 00:00:00        2.6                  15
    ## 10  2021 August Gwynns Falls… 2021-08-17 00:00:00        3.21                 15
    ## # ℹ 253 more rows
    ## # ℹ 6 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>

4.  Combine the dataset

``` r
final_merged2_df = 
  bind_rows(mrtrash_df, prtrash_df, gwtrash_df) |>
  janitor::clean_names()

final_merged2_df
```

    ## # A tibble: 1,032 × 14
    ##     year month wheel_name     date                weight_tons volume_cubic_yards
    ##    <dbl> <chr> <chr>          <dttm>                    <dbl>              <dbl>
    ##  1  2014 May   Mr. Trash Whe… 2014-05-16 00:00:00        4.31                 18
    ##  2  2014 May   Mr. Trash Whe… 2014-05-16 00:00:00        2.74                 13
    ##  3  2014 May   Mr. Trash Whe… 2014-05-16 00:00:00        3.45                 15
    ##  4  2014 May   Mr. Trash Whe… 2014-05-17 00:00:00        3.1                  15
    ##  5  2014 May   Mr. Trash Whe… 2014-05-17 00:00:00        4.06                 18
    ##  6  2014 May   Mr. Trash Whe… 2014-05-20 00:00:00        2.71                 13
    ##  7  2014 May   Mr. Trash Whe… 2014-05-21 00:00:00        1.91                  8
    ##  8  2014 May   Mr. Trash Whe… 2014-05-28 00:00:00        3.7                  16
    ##  9  2014 June  Mr. Trash Whe… 2014-06-05 00:00:00        2.52                 14
    ## 10  2014 June  Mr. Trash Whe… 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 1,022 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>

- The combined Trash Wheel dataset is a time-series data frame that
  aggregates collection metrics for three different wheels: Mr. Trash
  Wheel, Professor Trash Wheel, and Gwynnda. This dataset contains 1032
  observations, with key variables including the wheel identifier, the
  date, the amount of trash collected by weight, and specific item
  counts like plastic_bottles and cigarette_butts. Analysis of the
  individual wheels shows that the total weight of trash collected by
  Professor Trash Wheel amounts to 246.74 tons. Furthermore, the total
  number of cigarette butts collected by Gwynns in June of 2022 was
  18,120 butts.

# Problem 3

1.  First dataset

``` r
zipcode_df = read_csv(file = "./zillow_data/Zip Codes.csv") |> 
  janitor::clean_names() |> 
  rename(county_name = county) |> 
  select(-county_fips) |> 
  relocate(zip_code, county_name) |> 
  arrange(zip_code)

zipcode_df
```

    ## # A tibble: 322 × 6
    ##    zip_code county_name state_fips county_code file_date neighborhood           
    ##       <dbl> <chr>            <dbl> <chr>       <chr>     <chr>                  
    ##  1    10001 New York            36 061         7/25/07   Chelsea and Clinton    
    ##  2    10002 New York            36 061         7/25/07   Lower East Side        
    ##  3    10003 New York            36 061         7/25/07   Lower East Side        
    ##  4    10004 New York            36 061         7/25/07   Lower Manhattan        
    ##  5    10005 New York            36 061         7/25/07   Lower Manhattan        
    ##  6    10006 New York            36 061         7/25/07   Lower Manhattan        
    ##  7    10007 New York            36 061         7/25/07   Lower Manhattan        
    ##  8    10008 New York            36 061         7/25/07   <NA>                   
    ##  9    10009 New York            36 061         7/25/07   Lower East Side        
    ## 10    10010 New York            36 061         7/25/07   Gramercy Park and Murr…
    ## # ℹ 312 more rows

2.  Second dataset

``` r
rental_df = read_csv(file = "./zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv") |> 
  janitor::clean_names() |> 
  pivot_longer(
    x2015_01_31:x2024_08_31,
    names_to = "rental_date", 
    values_to = "rental_price") |> 
  mutate(
    county_name = stringr::str_replace(county_name, " County", ""),
    rental_date = stringr::str_replace(rental_date, "x", "")
  ) |> 
  separate(rental_date, into = c("year", "month", "day"), sep = "_") |> 
  mutate(
    month=as.integer(month),
    year=as.integer(year),
    day=as.integer(day)) |> 
  rename(zip_code = region_name) |> 
  relocate(zip_code, county_name) |> 
  select(-state, -region_type) |> 
  arrange(zip_code)

rental_df
```

    ## # A tibble: 17,284 × 11
    ##    zip_code county_name region_id size_rank state_name city    metro  year month
    ##       <dbl> <chr>           <dbl>     <dbl> <chr>      <chr>   <chr> <int> <int>
    ##  1    10001 New York        61615      4444 NY         New Yo… New …  2015     1
    ##  2    10001 New York        61615      4444 NY         New Yo… New …  2015     2
    ##  3    10001 New York        61615      4444 NY         New Yo… New …  2015     3
    ##  4    10001 New York        61615      4444 NY         New Yo… New …  2015     4
    ##  5    10001 New York        61615      4444 NY         New Yo… New …  2015     5
    ##  6    10001 New York        61615      4444 NY         New Yo… New …  2015     6
    ##  7    10001 New York        61615      4444 NY         New Yo… New …  2015     7
    ##  8    10001 New York        61615      4444 NY         New Yo… New …  2015     8
    ##  9    10001 New York        61615      4444 NY         New Yo… New …  2015     9
    ## 10    10001 New York        61615      4444 NY         New Yo… New …  2015    10
    ## # ℹ 17,274 more rows
    ## # ℹ 2 more variables: day <int>, rental_price <dbl>

3.  Merge the data

``` r
final_merged3_df = 
  zipcode_df |>
  left_join(rental_df, by = c("zip_code", "county_name"))

final_merged3_df
```

    ## # A tibble: 17,342 × 15
    ##    zip_code county_name state_fips county_code file_date neighborhood  region_id
    ##       <dbl> <chr>            <dbl> <chr>       <chr>     <chr>             <dbl>
    ##  1    10001 New York            36 061         7/25/07   Chelsea and …     61615
    ##  2    10001 New York            36 061         7/25/07   Chelsea and …     61615
    ##  3    10001 New York            36 061         7/25/07   Chelsea and …     61615
    ##  4    10001 New York            36 061         7/25/07   Chelsea and …     61615
    ##  5    10001 New York            36 061         7/25/07   Chelsea and …     61615
    ##  6    10001 New York            36 061         7/25/07   Chelsea and …     61615
    ##  7    10001 New York            36 061         7/25/07   Chelsea and …     61615
    ##  8    10001 New York            36 061         7/25/07   Chelsea and …     61615
    ##  9    10001 New York            36 061         7/25/07   Chelsea and …     61615
    ## 10    10001 New York            36 061         7/25/07   Chelsea and …     61615
    ## # ℹ 17,332 more rows
    ## # ℹ 8 more variables: size_rank <dbl>, state_name <chr>, city <chr>,
    ## #   metro <chr>, year <int>, month <int>, day <int>, rental_price <dbl>

- The resulting dataset is a tidy, time-series data frame containing
  rental price metrics across various geographic levels. It appears to
  combine Zillow rental data (indicated by columns like zip_code,
  region_id, and rental_price) with geographic identifiers like
  county_name and state_name. Each row represents a rental price
  observation for a specific ZIP code and month. This dataset includes a
  total of 17342 observations. Within these records, the data covers 320
  unique ZIP codes and 42 unique neighborhoods.

- 174 ZIP codes appear in the ZIP code dataset but not in the Zillow
  Rental Price dataset. The reason is that many large office towers or
  institutions in major cities have their own dedicated ZIP codes. These
  areas have no street-level residential rentals for Zillow to track.

4.  Make a table

``` r
top_drop_zips <-
final_merged3_df |>
  # 1. Filter for the two target months/years
mutate(
    # Combine year, month, and day columns into a proper Date object
    # We use make_date() since the component columns already exist
    date_full = make_date(year,month, day)
  ) |>
  
  # 2. Filter for the entire continuous range
  filter(
    date_full >= as.Date("2020-01-31") & date_full <= as.Date("2021-12-31")
  ) |>
  
  # 2. Select columns needed for pivoting and identification
  select(zip_code, date_full, county_name, neighborhood, rental_price, -year, -month, -day) |>
  
  # 3. Pivot the data from long to wide format
  pivot_wider(
    id_cols = c(zip_code, county_name, neighborhood),
    names_from = date_full,
    values_from = rental_price,
    names_prefix = "Price_" # Creates columns named Price_2020 and Price_2021
  ) |>
  
  # 4. Calculate the price drop (2021 - 2020)
  mutate(
    price_drop_Jan = `Price_2021-01-31` - `Price_2020-01-31`,
    price_drop_Feb = `Price_2021-02-28` - `Price_2020-02-29`,
    price_drop_Mar = `Price_2021-03-31` - `Price_2020-03-31`,
    price_drop_Apr = `Price_2021-04-30` - `Price_2020-04-30`,
    price_drop_May = `Price_2021-05-31` - `Price_2020-05-31`,
    price_drop_Jun = `Price_2021-06-30` - `Price_2020-06-30`,
    price_drop_Jul = `Price_2021-07-31` - `Price_2020-07-31`,
    price_drop_Aug = `Price_2021-08-31` - `Price_2020-08-31`,
    price_drop_Sep = `Price_2021-09-30` - `Price_2020-09-30`,
    price_drop_Oct = `Price_2021-10-31` - `Price_2020-10-31`,
    price_drop_Nov = `Price_2021-11-30` - `Price_2020-11-30`,
    price_drop_Dec = `Price_2021-12-31` - `Price_2020-12-31`
  )
```

5.  Compare each month

``` r
# 1.
top_drop_Jan <-
top_drop_zips |> 
  arrange(price_drop_Jan) |> 
  select(
    zip_code,
    borough = county_name,
    neighborhood,
    price_drop_Jan
  ) |>
  head(10)

top_drop_Jan
```

    ## # A tibble: 10 × 4
    ##    zip_code borough  neighborhood                  price_drop_Jan
    ##       <dbl> <chr>    <chr>                                  <dbl>
    ##  1    10007 New York Lower Manhattan                        -913.
    ##  2    10069 New York <NA>                                   -748.
    ##  3    10009 New York Lower East Side                        -714.
    ##  4    10016 New York Gramercy Park and Murray Hill          -712.
    ##  5    10001 New York Chelsea and Clinton                    -710.
    ##  6    10002 New York Lower East Side                        -710.
    ##  7    10004 New York Lower Manhattan                        -706.
    ##  8    10038 New York Lower Manhattan                        -698.
    ##  9    10012 New York Greenwich Village and Soho             -686.
    ## 10    10010 New York Gramercy Park and Murray Hill          -685.

``` r
#2.
top_drop_Feb <-
top_drop_zips |> 
    arrange(price_drop_Feb) |> 
    select(
    zip_code,
    borough = county_name,
    neighborhood,
    price_drop_Feb
  ) |>
  head(10)

top_drop_Feb
```

    ## # A tibble: 10 × 4
    ##    zip_code borough  neighborhood                  price_drop_Feb
    ##       <dbl> <chr>    <chr>                                  <dbl>
    ##  1    10007 New York Lower Manhattan                        -908.
    ##  2    10002 New York Lower East Side                        -745.
    ##  3    10009 New York Lower East Side                        -719.
    ##  4    10016 New York Gramercy Park and Murray Hill          -702.
    ##  5    10038 New York Lower Manhattan                        -702.
    ##  6    10004 New York Lower Manhattan                        -685.
    ##  7    10001 New York Chelsea and Clinton                    -674.
    ##  8    10012 New York Greenwich Village and Soho             -671.
    ##  9    10003 New York Lower East Side                        -667.
    ## 10    10069 New York <NA>                                   -649.

``` r
#3.
top_drop_Mar <-
top_drop_zips |> 
    arrange(price_drop_Mar) |> 
    select(
    zip_code,
    borough = county_name,
    neighborhood,
    price_drop_Mar
  ) |>
  head(10)

top_drop_Mar
```

    ## # A tibble: 10 × 4
    ##    zip_code borough  neighborhood                  price_drop_Mar
    ##       <dbl> <chr>    <chr>                                  <dbl>
    ##  1    10007 New York Lower Manhattan                        -773.
    ##  2    10012 New York Greenwich Village and Soho             -702.
    ##  3    10009 New York Lower East Side                        -680.
    ##  4    10002 New York Lower East Side                        -677.
    ##  5    10013 New York Greenwich Village and Soho             -676.
    ##  6    10001 New York Chelsea and Clinton                    -638.
    ##  7    10016 New York Gramercy Park and Murray Hill          -632.
    ##  8    10036 New York Chelsea and Clinton                    -625.
    ##  9    10038 New York Lower Manhattan                        -624.
    ## 10    10011 New York Chelsea and Clinton                    -620.

``` r
#4.
top_drop_Apr <-
top_drop_zips |> 
    arrange(price_drop_Apr) |> 
    select(
    zip_code,
    borough = county_name,
    neighborhood,
    price_drop_Apr
  ) |>
  head(10)

top_drop_Apr
```

    ## # A tibble: 10 × 4
    ##    zip_code borough  neighborhood                  price_drop_Apr
    ##       <dbl> <chr>    <chr>                                  <dbl>
    ##  1    10013 New York Greenwich Village and Soho             -614.
    ##  2    10012 New York Greenwich Village and Soho             -612.
    ##  3    10007 New York Lower Manhattan                        -588.
    ##  4    10009 New York Lower East Side                        -561.
    ##  5    10002 New York Lower East Side                        -554.
    ##  6    10036 New York Chelsea and Clinton                    -551.
    ##  7    10280 New York Lower Manhattan                        -535.
    ##  8    10003 New York Lower East Side                        -525.
    ##  9    10022 New York Gramercy Park and Murray Hill          -520.
    ## 10    10001 New York Chelsea and Clinton                    -507.

``` r
#5. 
top_drop_May <-
top_drop_zips |> 
    arrange(price_drop_May) |> 
    select(
    zip_code,
    borough = county_name,
    neighborhood,
    price_drop_May
  ) |>
  head(10)

top_drop_May
```

    ## # A tibble: 10 × 4
    ##    zip_code borough  neighborhood                  price_drop_May
    ##       <dbl> <chr>    <chr>                                  <dbl>
    ##  1    10006 New York Lower Manhattan                        -450.
    ##  2    10012 New York Greenwich Village and Soho             -448.
    ##  3    10022 New York Gramercy Park and Murray Hill          -407.
    ##  4    10009 New York Lower East Side                        -404.
    ##  5    10013 New York Greenwich Village and Soho             -391.
    ##  6    10017 New York Gramercy Park and Murray Hill          -380.
    ##  7    10028 New York Upper East Side                        -365.
    ##  8    10002 New York Lower East Side                        -361.
    ##  9    10038 New York Lower Manhattan                        -361.
    ## 10    10065 New York Upper East Side                        -357.

``` r
#6.
top_drop_Jun <-
top_drop_zips |> 
    arrange(price_drop_Jun) |> 
    select(
    zip_code,
    borough = county_name,
    neighborhood,
    price_drop_Jun
  ) |>
  head(10)

top_drop_Jun
```

    ## # A tibble: 10 × 4
    ##    zip_code borough  neighborhood                  price_drop_Jun
    ##       <dbl> <chr>    <chr>                                  <dbl>
    ##  1    10022 New York Gramercy Park and Murray Hill          -283.
    ##  2    10128 New York Upper East Side                        -268.
    ##  3    10029 New York East Harlem                            -257.
    ##  4    10028 New York Upper East Side                        -254.
    ##  5    10075 New York Upper East Side                        -251.
    ##  6    10065 New York Upper East Side                        -249.
    ##  7    10006 New York Lower Manhattan                        -233.
    ##  8    10027 New York Central Harlem                         -220.
    ##  9    10021 New York Upper East Side                        -215.
    ## 10    10005 New York Lower Manhattan                        -212.

``` r
#7.
top_drop_Jul <-
top_drop_zips |>
    arrange(price_drop_Jul) |> 
    select(
    zip_code,
    borough = county_name,
    neighborhood,
    price_drop_Jul
  ) |>
  head(10)

top_drop_Jul
```

    ## # A tibble: 10 × 4
    ##    zip_code borough  neighborhood                  price_drop_Jul
    ##       <dbl> <chr>    <chr>                                  <dbl>
    ##  1    10029 New York East Harlem                           -152. 
    ##  2    10128 New York Upper East Side                       -131. 
    ##  3    10065 New York Upper East Side                       -123. 
    ##  4    10039 New York Central Harlem                        -121. 
    ##  5    10028 New York Upper East Side                       -116. 
    ##  6    10027 New York Central Harlem                        -106. 
    ##  7    11106 Queens   Northwest Queens                      -106. 
    ##  8    10022 New York Gramercy Park and Murray Hill         -106. 
    ##  9    10037 New York Central Harlem                        -101. 
    ## 10    10040 New York Inwood and Washington Heights          -97.1

``` r
#8.
top_drop_Aug <-
top_drop_zips |> 
    arrange(price_drop_Aug) |> 
    select(
    zip_code,
    borough = county_name,
    neighborhood,
    price_drop_Aug
  ) |>
  head(10)

top_drop_Aug
```

    ## # A tibble: 10 × 4
    ##    zip_code borough  neighborhood                  price_drop_Aug
    ##       <dbl> <chr>    <chr>                                  <dbl>
    ##  1    11355 Queens   North Queens                           -73.8
    ##  2    10034 New York Inwood and Washington Heights          -67.0
    ##  3    10039 New York Central Harlem                         -63.5
    ##  4    10040 New York Inwood and Washington Heights          -60.4
    ##  5    10037 New York Central Harlem                         -57.3
    ##  6    10033 New York Inwood and Washington Heights          -56.4
    ##  7    10029 New York East Harlem                            -40.9
    ##  8    11106 Queens   Northwest Queens                       -40.2
    ##  9    11220 Kings    Sunset Park                            -39.4
    ## 10    11104 Queens   Northwest Queens                       -30.6

``` r
#9.
top_drop_Sep <-
top_drop_zips |> 
    arrange(price_drop_Sep) |> 
    select(
    zip_code,
    borough = county_name,
    neighborhood,
    price_drop_Sep
  ) |>
  head(10)

top_drop_Sep
```

    ## # A tibble: 10 × 4
    ##    zip_code borough  neighborhood                  price_drop_Sep
    ##       <dbl> <chr>    <chr>                                  <dbl>
    ##  1    11355 Queens   North Queens                          -74.0 
    ##  2    10034 New York Inwood and Washington Heights         -41.1 
    ##  3    10039 New York Central Harlem                        -30.8 
    ##  4    11104 Queens   Northwest Queens                      -28.4 
    ##  5    10040 New York Inwood and Washington Heights         -10.8 
    ##  6    10462 Bronx    Southeast Bronx                        -8.24
    ##  7    10037 New York Central Harlem                         -1.25
    ##  8    11377 Queens   West Queens                             1.40
    ##  9    11105 Queens   Northwest Queens                        4.60
    ## 10    10304 Richmond Stapleton and St. George               14.0

``` r
#10.
top_drop_Oct <-
top_drop_zips |> 
    arrange(price_drop_Oct) |> 
    select(
    zip_code,
    borough = county_name,
    neighborhood,
    price_drop_Oct
  ) |>
  head(10)

top_drop_Oct
```

    ## # A tibble: 10 × 4
    ##    zip_code borough  neighborhood                  price_drop_Oct
    ##       <dbl> <chr>    <chr>                                  <dbl>
    ##  1    11355 Queens   North Queens                          -57.5 
    ##  2    10034 New York Inwood and Washington Heights          -4.71
    ##  3    11214 Kings    Southwest Brooklyn                     14.3 
    ##  4    11104 Queens   Northwest Queens                       21.6 
    ##  5    11374 Queens   West Central Queens                    22.1 
    ##  6    10040 New York Inwood and Washington Heights          26.3 
    ##  7    11377 Queens   West Queens                            27.1 
    ##  8    10039 New York Central Harlem                         28.6 
    ##  9    10458 Bronx    Bronx Park and Fordham                 35.3 
    ## 10    11375 Queens   West Central Queens                    39.5

``` r
#11.
top_drop_Nov <-
top_drop_zips |> 
    arrange(price_drop_Nov) |> 
    select(
    zip_code,
    borough = county_name,
    neighborhood,
    price_drop_Nov
  ) |>
  head(10)

top_drop_Nov
```

    ## # A tibble: 10 × 4
    ##    zip_code borough  neighborhood                  price_drop_Nov
    ##       <dbl> <chr>    <chr>                                  <dbl>
    ##  1    11355 Queens   North Queens                          -7.15 
    ##  2    11377 Queens   West Queens                           -0.208
    ##  3    11214 Kings    Southwest Brooklyn                    20.2  
    ##  4    10034 New York Inwood and Washington Heights         27.2  
    ##  5    10458 Bronx    Bronx Park and Fordham                27.3  
    ##  6    11435 Queens   Jamaica                               27.7  
    ##  7    10467 Bronx    Bronx Park and Fordham                37.8  
    ##  8    11105 Queens   Northwest Queens                      60.9  
    ##  9    10039 New York Central Harlem                        61.6  
    ## 10    11220 Kings    Sunset Park                           61.8

``` r
#12.
top_drop_Dec <-
top_drop_zips |>
    arrange(price_drop_Dec) |> 
    select(
    zip_code,
    borough = county_name,
    neighborhood,
    price_drop_Dec
  ) |>
  head(10)

top_drop_Dec
```

    ## # A tibble: 10 × 4
    ##    zip_code borough  neighborhood                  price_drop_Dec
    ##       <dbl> <chr>    <chr>                                  <dbl>
    ##  1    11432 Queens   Jamaica                                 6.94
    ##  2    10458 Bronx    Bronx Park and Fordham                  8.86
    ##  3    10467 Bronx    Bronx Park and Fordham                 22.1 
    ##  4    11377 Queens   West Queens                            34.7 
    ##  5    11355 Queens   North Queens                           37.1 
    ##  6    11435 Queens   Jamaica                                41.6 
    ##  7    10034 New York Inwood and Washington Heights          57.5 
    ##  8    11220 Kings    Sunset Park                            66.2 
    ##  9    11354 Queens   North Queens                           72.2 
    ## 10    11214 Kings    Southwest Brooklyn                     91.0

``` r
# The names here become the sheet names in Excel.
data_to_export <- list(
  "top_drop_Jan" = top_drop_Jan,
  "top_drop_Feb" = top_drop_Feb,
  "top_drop_Mar" = top_drop_Mar,
  "top_drop_Apr" = top_drop_Apr,
  "top_drop_May" = top_drop_May,
  "top_drop_Jun" = top_drop_Jun,
  "top_drop_Jul" = top_drop_Jul,
  "top_drop_Aug" = top_drop_Aug,
  "top_drop_Sep" = top_drop_Sep,
  "top_drop_Oct" = top_drop_Oct,
  "top_drop_Nov" = top_drop_Nov,
  "top_drop_Dec" = top_drop_Dec
)

# --- 3. Export the list to a single Excel file ---
writexl::write_xlsx(
  x = data_to_export, 
  path = "Price_month_Example.xlsx"
)
```

- The period from January 2020 to early 2021 saw the largest rental
  price declines concentrated in high-density Manhattan neighborhoods.
  However, as noted by the data showing positive price differences after
  August 2021, this trend quickly stabilized and shifted into a rebound.
  This recovery might be fueled by vaccine availability.
