---
title: "p8105_hw2_th3147"
author: "Te-Hsuan Huang"
date: "2025-09-27"
output: github_document
---

# Problem 1

1. First dataset

```{r}
library(tidyverse)

polsmonth_df = read_csv(file = "./fivethirtyeight_datasets/pols-month.csv") |> 
  janitor::clean_names() |> 
  separate(mon, into = c("year", "month", "day"), sep = "-") |> 
 mutate( 
   year = as.numeric(year),
    month = case_match(
      month,
      "01" ~ "jan",
      "02" ~ "feb",
      "03" ~ "mar",
      "04" ~ "apr",
      "05" ~ "may",
      "06" ~ "jun",
      "07" ~ "jul",
      "08" ~ "aug",
      "09" ~ "sep",
      "10" ~ "oct",
      "11" ~ "nov",
      "12" ~ "dec"
    ), 
    
    president = case_match(
      prez_dem,
      1 ~ "dem",
      0 ~ "gop")) |> 
    select(-prez_dem, -prez_gop, -day)

polsmonth_df
  
```

* make sure the lower case in month.

2.second dataset

```{r}
snp_df = read_csv(file = "./fivethirtyeight_datasets/snp.csv") |> 
  janitor::clean_names() |> 
  separate(date, into = c("month", "day", "year"), sep = "/") |>
  mutate(
    year = as.integer(paste0("20", year)),
    year = as.numeric(year),
    month = case_match(
      month,
      "1" ~ "jan",
      "2" ~ "feb",
      "3" ~ "mar",
      "4" ~ "apr",
      "5" ~ "may",
      "6" ~ "jun",
      "7" ~ "jul",
      "8" ~ "aug",
      "9" ~ "sep",
      "10" ~ "oct",
      "11" ~ "nov",
      "12" ~ "dec"
    )) |> 
      select(-day) |>
      arrange (year, month) |> 
      relocate(year, month)

snp_df
```

* paste0: is a function in R used to concatenate (join together) character strings.

* make sure the lower case in month.


3. Third dataset

```{r}
unemploy_df = read_csv(file = "./fivethirtyeight_datasets/unemployment.csv") |> 
  janitor::clean_names() |> 
  pivot_longer(
    jan:dec,
    names_to = "month", 
    values_to = "unemployment_rate") |> 
  relocate(year, month) |>
  arrange(year, month)

unemploy_df
```

4. Join the dataset

```{r}
final_merged_df = 
  polsmonth_df |>
  left_join(snp_df, by = c("year", "month")) |>
  left_join(unemploy_df, by = c("year", "month"))

final_merged_df
```

* Keep in mind: the features of year and month in each dataset should be same.
